set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'mocha'

# Configure the status bar modules
set -g @catppuccin_window_status_style "slanted"
set -g @catppuccin_status_modules_right "application session date_time"

# hide the green/yellow status bar
set -g status off

# enable mouse scrolling
set -g mouse on

# Fix for Kitty colors (ensures 256 colors show up correctly in Tmux)
set -g default-terminal "xterm-kitty"


# Pass cursor shape sequences to Kitty
set -as terminal-overrides ',xterm-kitty:Ss=\E[%p1%d q:Se=\E[2 q'
